
// Auto-generated by AutoPilot on 07-08-2023 at 01:33:29

const express = require('express');
const router = express.Router();

// Route to return a review for cracking the coding interview and rate it out of 10
router.get('/review', (req, res) => {
    const review = "Cracking the Coding Interview is an excellent resource for anyone looking to practice technical interview questions. I give it 10/10!";
    res.send(review);
});

module.exports = router;